POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Exploring the Wonders of the JavaScript Ecosystem",
    "author": "Aleksi Huusko",
    "url": "https://example.com/exploring-javascript-ecosystem",
    "likes": 42,
    "userId": "66938f3cf2d029135c2f8054"
}
